const users = [
  {
    id: 1,
    login: "ИвановИИ",
    name: "Иван",
    surname: "Иванов",
    lastname: "Иванович",
    group: "",
    password: "123",
    role: "student",
  },
  {
    id: 2,
    login: "АлександровАА",
    name: "Александр",
    surname: "Александров",
    lastname: "Александрович",
    group: "БО241ПИН",
    password: "123",
    role: "teacher",
  },
  {
    id: 3,
    login: "АндреевАА",
    name: "Андрей",
    surname: "Андреев",
    lastname: "Андреевич",
    group: "БО241ИСТ",
    password: "123",
    role: "student",
  },
  {
    id: 4,
    login: "ТхорикАА",
    name: "Александр",
    surname: "Тхорик",
    lastname: "Александрович",
    group: "БО241ПИН",
    password: "123",
    role: "student",
  },
  {
    id: 5,
    login: "ЛогуновИИ",
    name: "Иван",
    surname: "Логунов",
    lastname: "Иванович",
    group: "БО241ИСТ",
    password: "123",
    role: "student",
  },
];

module.exports = users;
